name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gas-buddy/yarn-build-action@v5
        with:
          npm-token: ${{ secrets.npm_token }}
          skip-test: true
          skip-lint: true

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gas-buddy/yarn-build-action@v5
        with:
          npm-token: ${{ secrets.npm_token }}
          skip-test: true
          skip-lint: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

