name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version-file: .nvmrc
      - run: yarn

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

